domain: "###ZARF_VAR_DOMAIN###"

registryCredentials:
  registry: "###ZARF_REGISTRY###"
  username: "zarf-pull"
  password: "###ZARF_REGISTRY_AUTH_PULL###"

git:
  existingSecret: "private-git-server"

networkPolicies:
  enabled: false
  # When in prod use a real CIDR. Don't do this, it isn't secure. This is done here since it is a demo and the CIDR changes based on which Linux distro you are running on.
  controlPlaneCidr: "0.0.0.0/0"
  nodeCidr: "0.0.0.0/0"
  vpcCidr: "0.0.0.0/0"

kiali:
  enabled: false

istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"

clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false

# EFK -> PLG, see https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/1.39.0/docs/guides/using-bigbang/efk-plg-logging-migration.md
logging:
  enabled: true
  values:
    elasticsearch:
      master:
        persistence:
          storageClassName: "local-path"
      data:
        persistence:
          storageClassName: "local-path"
      ingest:
        persistence:
          storageClassName: "local-path"
      ml:
        persistence:
          storageClassName: "local-path"

eckoperator:
  enabled: true
fluentbit:
  enabled: true
jaeger:
  enabled: true
loki:
  enabled: false
promtail:
  enabled: false
tempo:
  enabled: false