apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dataplane-ek
  namespace: dataplane-ek
spec:
  interval: 5m
  url: https://repo1.dso.mil/platform-one/big-bang/apps/core/elasticsearch-kibana.git
  ref:
    tag: "0.7.1-bb.0"
  secretRef:
    name: private-git-server
