name: Create Zarf Package

inputs:
  registry_username:
    required: true
  registry_password:
    required: true
  registry_url:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        "$GITHUB_ACTION_PATH/registry-login.sh" "${{ inputs.registry_username }}" "${{ inputs.registry_password }}" "${{ inputs.registry_url }}"
      shell: bash
