name: Create Zarf Package

inputs:
  registry_username:
    required: true
  registry_password:
    required: true
  registry_url:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/registry-login.sh ${{ inputs.registry_username }} ${{ inputs.registry_password }} ${{ inputs.registry_url }}
      shell: bash
