name: Package DCO Foundation
run-name: ${{github.actor}} is building the DCO Foundation Zarf Package
on: 
  workflow_dispatch:
  push:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-zarf
      - uses: ./.github/actions/registry-login
        with:
          registry_username: ${{secrets.REGISTRY1_USERNAME}}
          registry_password: ${{secrets.REGISTRY1_PASSWORD}}
          registry_url: registry1.dso.mil
      - uses: ./.github/actions/package-create
      - uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64
          rootdir: ""    # defaults to "PWD"
          workdir: ""    # defaults to "PWD/unfor19-awscli"
      - uses: ./.github/actions/s3-publish
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          aws_bucket: ${{secrets.AWS_BUCKET}}
          source: "zarf-package-dco-foundation-amd64.tar.zst"
          destination: "${{github.repository}}/${{github.ref_name}}/zarf-package-dco-foundation-amd64.tar.zst"
          
      # - uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: ${{secrets.AWS_ACCESS_KEY}}
      #     aws_secret_access_key: ${{secrets.AWS_SECRET_KEY}}
      #     aws_bucket: ${{secrets.AWS_BUCKET}}
      #     source_dir: "out"
      #     destination_dir: "${{github.repository}}/${{github.ref_name}}/out"
