name: Package DCO Foundation
run-name: ${{ github.actor }} is building the DCO Foundation Zarf Package
on: 
  workflow_dispatch:
  push:



jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-zarf
      - uses: ./.github/actions/registry-login
        with:
          registry1_username: ${{ secrets.REGISTRY1USERNAME }}
          registry1_password: ${{ secrets.REGISTRY1PASSWORD }}
      - uses: ./.github/actions/package-create
