name: Package DCO Foundation
run-name: ${{github.actor}} is building the DCO Foundation Zarf Package
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
env:
  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
  ZARF_PACKAGE: zarf-package-dco-foundation-amd64.tar.zst
jobs:
  package-create:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.22.2

      - name: Login to Registry One
        run: |
          zarf tools registry login \
            -u "${{secrets.REGISTRY1_USERNAME}}" \
            -p "${{secrets.REGISTRY1_PASSWORD}}" \
            "registry1.dso.mil"

      - name: Create Zarf Package
        run: |
          # cleanup and init a tmp dir
          rm -rf tmp
          mkdir tmp

          # remove any cached version of dco_foundation to avoid push warnings (known zarf issue)
          rm -rf ~/.zarf-cache/repos/dco-foundation*

          # build the zarf package
          zarf package create \
            --set BRANCH="${{ env.BRANCH_NAME }}" \
            --confirm \
            --tmpdir $PWD/tmp \
            --skip-sbom

          # cleanup tmp dir
          rm -rf ./tmp

      - name: Save Package to S3
        run: |
          aws s3 cp --no-progress "${{ env.ZARF_PACKAGE }}" "${{ env.S3_PATH }}/${{ env.ZARF_PACKAGE }}"
