name: Package DCO Foundation
run-name: ${{github.actor}} is building the DCO Foundation Zarf Package
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
env:
  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
  IMAGE_NAME: 765814079306.dkr.ecr.us-east-1.amazonaws.com/mixmode
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
  ZARF_PACKAGE: zarf-package-dco-foundation-amd64.tar.zst

jobs:

  package-create:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.22.2

      - name: Login to Registry One
        uses: ./.github/actions/registry-login
        with:
          registry_username: ${{secrets.REGISTRY1_USERNAME}}
          registry_password: ${{secrets.REGISTRY1_PASSWORD}}
          registry_url: registry1.dso.mil

      - name: Create Zarf Package
        run: |
          if [ -d "./tmp" ]; then
            rm -rf ./tmp
          fi
          mkdir tmp
          zarf package create --set BRANCH="${{ env.BRANCH_NAME }}" --confirm --tmpdir $PWD/tmp
          rm -rf ./tmp

      - name: Save Package to S3
        run: |
          aws s3 cp --no-progress "${{ env.ZARF_PACKAGE }}" "${{ env.S3_PATH }}/${{ env.ZARF_PACKAGE }}"
