name: Package DCO Foundation
run-name: ${{github.actor}} is building the DCO Foundation Zarf Package
on: 
  workflow_dispatch:
  push:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - run: echo "env $GITHUB_REPOSITORY/$GITHUB_REF_NAME"
        shell: bash
      - run: echo "env ${{github.repository}}/${{github.ref_name}}"
        shell: bash
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-zarf
      - uses: ./.github/actions/registry-login
        with:
          registry_username: ${{secrets.REGISTRY1_USERNAME}}
          registry_password: ${{secrets.REGISTRY1_PASSWORD}}
          registry_url: registry1.dso.mil
      - uses: ./.github/actions/package-create
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_KEY}}
          aws_bucket: ${{secrets.AWS_BUCKET}}
          source_dir: "zarf-package-dco-foundation-amd64.tar.zst"
          destination_dir: "${{env.GITHUB_REPOSITORY}}/${{env.GITHUB_REF_NAME}}/zarf-package-dco-foundation-amd64.tar.zst"
